name: unix_single_instance
description: A library which uses unix sockets to ensure a single instance
version: 0.0.4
repository: https://github.com/arran4/dart_unix_single_instance
homepage: https://github.com/arran4/dart_unix_single_instance

environment:
  sdk: '>=3.3.0 <4.0.0'
  # Because of path_provider -_-
  flutter: ">=2.5.0"

dependencies:
  args: '>=2.7.0 <4.0.0'
  path: '>=1.9.1 <3.0.0'
  path_provider: '>=2.1.5 <4.0.0'

dev_dependencies:
  test: ^1.30.0
  lints: '>=6.0.0 <8.0.0'

# This package supports only Linux and macOS.
platforms:
  linux:
  macos: